### ISSUE TITLE
Script startup time is too high

### ISSUE THREAD

**Issue by korniltsev** [dhelleberg/android-scripts#1]
Now compilation time is so much bigger then script execution time
Please consider to compile the script so users don't have recompile it on every run.

**Comment by dhelleberg** [comment]
Yes, groovy and the JVM do need time to spin up. You can fix that by using groovyclient, see
http://kobo.github.io/groovyserv/index.html

On MacOSX just run

```
brew install groovyserv
groovyclient /usr/local/bin/devtools
```

and your startuptimes are fine:

```
dhelleberg@local ~> time devtools
    0.90 real         1.56 user         0.13 sys

dhelleberg@local ~ [255]> time groovyclient /usr/local/bin/devtools
    0.06 real         0.00 user         0.00 sys
```

**Comment by korniltsev** [comment]
no thanks ;)
