### ISSUE TITLE
where is  adb option document

### ISSUE THREAD

**Issue by pepperer** [dhelleberg/android-scripts#8]

**Comment by dhelleberg** [comment]
what exactly do you mean?

**Comment by pepperer** [comment]
> what exactly do you mean?

how did your find these adb command

**Comment by dhelleberg** [comment]
Most of them are taken from the AOSP source code. check how the developer options work and you can get most of the information from there

**Comment by pepperer** [comment]
Ok. thank you for your code and advice.
Now I use shell to achieve some function. (its no need groovy env). 
its my code : https://github.com/pepperer/shelljs/blob/master/src/android.sh
